version: '3.8'
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crp_price_database_development
    ports:
      - "5432:5432"

  redis:
    image: redis:5.3
    ports:
      - "6379:6379"

  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0' -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/crp_price_database_development
      REDIS_URL: redis://localhost:6379

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: redis://localhost:6379
    volumes:
      - .:/app

volumes:
  postgres_data: