default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  port: 5432

development:
  <<: *default
  database: crp_price_database_development

test:
  <<: *default
  database: crp_price_database_test
